config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'

  resources :accounts do
    get :inactive_landing
    
    resources :products do
      delete :color
      delete :size
      post :assign_colors
      post :assign_sizes
    end
    get :order_form
    resources :orders do
      get :shipping_details
      post :shipping_details_save
      resources :order_items do
        delete :delete_item

        collection { post :create_multiple }
      end
      get :order_invoice_pdf
    end

  end

  resources :carts do
  end


  resources :colors

  resources :sizes

  resources :product_logos

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :account

  before_create :set_order_status
  before_save :update_subtotal

  enum status: [:started, :placed, :shipped, :cancelled]



  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private

  def set_order_status
    self.status = 0
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
    @account = @order.account
    @products = @account.products.order(:ordering_number)
    @order_items = @order.order_items
  end

  def new
    @account = Account.find(params[:account_id])
    @products = @account.products.order(:ordering_number)
    @order = @account.orders.new(account_id: @account)
    if !@account.active?
      redirect_to @account
    end

  end

  def create
    @account = Account.find(params[:account_id])
    @order = @account.orders.new(order_params)
    @product_logo = @account.product_logos.find(params[:order][:id])
    @order.assign_attributes(product_logo: @product_logo.product_logo_image, product_logo_name: @product_logo.name)
    if params[:order][:same_as_billing]
      @order.assign_attributes(
      shipping_first_name: params[:order][:billing_first_name],
      shipping_last_name: params[:order][:billing_last_name],
      shipping_email: params[:order][:billing_email],
      shipping_phone_number: params[:order][:billing_phone_number] ,
      shipping_address_line_1: params[:order][:billing_address_line_1],
      shipping_address_line_2: params[:order][:billing_address_line_2],
      shipping_city: params[:order][:billing_city],
      shipping_state: params[:order][:billing_state],
      shipping_zip_code: params[:order][:billing_zip_code],
      shipping_branch_number: params[:order][:billing_branch_number])
    end

    if @order.save
      redirect_to account_order_path(@account, @order.id), notice: "Order Process has begun successfully."
    else
      redirect_to @account, alert: "Order Not Created."
    end
  end

  def shipping_details
    @order = Order.find(params[:order_id])
    @order_items = @order.order_items
    @account = @order.account
  end

  def shipping_details_save
    @order = Order.find(params[:order_id])
    @account = @order.account
    @order.assign_attributes(order_params)
    @product_logo = @account.product_logos.find(params[:order][:id])
    @order.assign_attributes(product_logo: @product_logo.product_logo_image, product_logo_name: @product_logo.name)
    @order.assign_attributes(status: 1)
    if @order.save
      pdf = OrderInvoicePdf.new(@account, @order, view_context)
      OrderMailer.order_email(@account.id, @order.id, pdf).deliver
      InvoiceMailer.invoice_email(@account.id, @order.id, pdf).deliver
      redirect_to @account, notice: 'Your order has been placed. Please check your email for receipt of the order confirmation.'
    else
      redirect_to @order, notice: 'There was an error with placing the order.  Please try again.'
    end
  end

  def order_invoice_pdf
    @account = Account.find(params[:account_id])
    @order = Order.find(params[:order_id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderInvoicePdf.new(@account, @order, view_context)
        send_data pdf.render, filename: "#{ @account.business_name }_order_#{ @order.id }.pdf",
                              type: "application/pdf",
                              disposition: "inline"
      end
    end
  end

  private

  def order_params
    params.require(:order).permit(:shipping_first_name, :shipping_last_name, :shipping_email, :shipping_phone_number, :shipping_address_line_1, :shipping_address_line_2, :shipping_city, :shipping_state, :shipping_zip_code, :billing_first_name, :billing_last_name, :billing_email, :billing_phone_number, :billing_address_line_1, :billing_address_line_2, :billing_city, :billing_state, :billing_zip_code, :order_id, :account_id, :same_as_billing,  :status, :subtotal, :tax, :shipping, :total, :shipping_branch_number, :billing_branch_number, :product_logo, :product_logo_name, :pc_id_number)
  end

end

app/helpers/order_helper.rb
module OrderHelper
end

app/views/orders/new.html.erb
<%= render partial: 'layouts/header', locals: { account: @account, order: @order } %>
<div class="container">
  <br>
  <%= form_for [@account, @order] do |f| %>
  <div class="row">
    <div class="col-4 offset-1">
      <h6>Billing Details: </h6>
      <br>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :billing_first_name, class: 'form-control', :placeholder => "First name", required: true %>
            </div>
            <div class="col-6">
              <%= f.text_field :billing_last_name, class: 'form-control', :placeholder => "Last name", required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-8">
              <%= f.text_field :billing_address_line_1, class: 'form-control', :placeholder => "Address", required: true %>
            </div>
            <div class="col-4">
              <%= f.text_field :billing_address_line_2, class: 'form-control', :placeholder => "Apt/Bld #"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :billing_city, class: 'form-control', :placeholder => "City", required: true %>
            </div>
            <div class="col-6">
              <%= f.text_field :billing_state, class: 'form-control', :placeholder => "State", required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-4">
              <%= f.text_field :billing_zip_code, class: 'form-control', :placeholder => "Zip code", required: true %>
            </div>
            <div class="col-8">
              <%= f.text_field :billing_phone_number, class: 'form-control', :placeholder => "Phone number", required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.text_field :billing_email, class: 'form-control', :placeholder => "Email address", required: true %>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :billing_branch_number, class: 'form-control', :placeholder => "Billing Branch #", required: true %>
            </div>
            <% if @account.require_pc_id_number%>
              <div class="col-6">
                <%= f.text_field :pc_id_number, class: 'form-control', :placeholder => "PC ID #", required:true %>
              </div>
              <% end %>
          </div>
        </div>


        <br>

      </div>
    <div class="col-4 offset-2">
      <h6>Shipping Details:</h6>
      <%= f.label :same_as_billing %>
      <%= f.check_box :same_as_billing %>
      <br>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :shipping_first_name, class: 'form-control', :placeholder => "First name" %>
            </div>
            <div class="col-6">
              <%= f.text_field :shipping_last_name, class: 'form-control', :placeholder => "Last name" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-8">
              <%= f.text_field :shipping_address_line_1, class: 'form-control', :placeholder => "Address" %>
            </div>
            <div class="col-4">
              <%= f.text_field :shipping_address_line_2, class: 'form-control', :placeholder => "Apt/Bld #"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :shipping_city, class: 'form-control', :placeholder => "City" %>
            </div>
            <div class="col-6">
              <%= f.text_field :shipping_state, class: 'form-control', :placeholder => "State"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-4">
              <%= f.text_field :shipping_zip_code, class: 'form-control', :placeholder => "Zip code" %>
            </div>
            <div class="col-8">
              <%= f.text_field :shipping_phone_number, class: 'form-control', :placeholder => "Phone number" %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <%= f.text_field :shipping_email, class: 'form-control', :placeholder => "Email address" %>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :shipping_branch_number, class: 'form-control', :placeholder => "Shipping Branch #" %>
            </div>

          </div>
        </div>
        <br>
      </div>
  </div>
  <div class="row justify-content-md-center">
    <div class="form-group">
      <%= f.label 'Please choose logo for items:' %>
      <%= f.select(:id, options_from_collection_for_select(@account.product_logos, :id, :name), {:include_blank => 'Choose Logo'},  class: "form-control", required: true ) %>
    </div>
  </div>
  <% unless @account.order_special_message.nil? %>
    <div class="row justify-content-md-center">
        <b><p><%= @account.order_special_message %></p></b>
    </div>
  <% end %>
  <div class="row justify-content-md-center">
    <div class="actions">
      <%= f.submit "Start Order", class: 'btn add-to-cart-button'%>
    </div>
  </div>
  <% end %>
</div>
<br>

app/views/orders/shipping_details.html.erb
<div class="account-header">
  <div class="d-flex justify-content-start">
      <div class="col-1 p-2 offset-1">
        <%= image_tag(@account.logo_url, class: 'd-flex align-self-center header-logo-image' )%>
      </div>
      <div class="col-4 p-3">
        <h1><%= @account.business_name %></h1>
        <h3 class="text-muted"> <%= @account.order_form_subheading %>    </h3>
        <p class="text-muted">Orders due by <%= @account.try(:orders_due_by).try(:strftime, "%B %d, %Y") %></p>
      </div>
      <div class="col-3 ml-auto p-3">
        <% if !@order.new_record? %>
          <%= link_to "Check Out", cart_path(order_id: @order.id, id: @account), class: 'cart-image' %>
          <%= link_to '', cart_path(order_id: @order.id, id: @account), class: 'fa fa-shopping-cart fa-3x fa-fw cart-image' %>
          <%= number_to_currency(@order.subtotal) %>
        <% end %>
      </div>
  </div>
</div>

</div>
<div class="container">
  <br>
  <div class="row">
    <div class="col-6">
      <h6>Shipping Details: </h6>
      <br>
      <%= form_for :order , :url => account_order_shipping_details_save_path(@account, @order) do |f| %>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :shipping_first_name, class: 'form-control', :placeholder => :shipping_first_name, required: true %>
            </div>
            <div class="col-6">
              <%= f.text_field :shipping_last_name, class: 'form-control', :placeholder => :shipping_last_name, required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-8">
              <%= f.text_field :shipping_address_line_1, class: 'form-control', :placeholder => "Address", required: true %>
            </div>
            <div class="col-4">
              <%= f.text_field :shipping_address_line_2, class: 'form-control', :placeholder => "Apt/Bld #"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :shipping_city, class: 'form-control', :placeholder => :shipping_city, required: true %>
            </div>
            <div class="col-3">
              <%= f.text_field :shipping_state, class: 'form-control', :placeholder => :shipping_state, required: true %>
            </div>
            <div class="col-3">
              <%= f.text_field :shipping_zip_code, class: 'form-control', :placeholder => :shipping_zip_code, required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :shipping_phone_number, class: 'form-control', :placeholder => :shipping_phone_number, required: true %>
            </div>
            <div class="col-6">
              <%= f.text_field :shipping_email, class: 'form-control', :placeholder => "Email address", required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
              <div class="col-6">
                <label>Shipping Branch #:</label>
                <%= f.text_field :shipping_branch_number, class: 'form-control', :placeholder => "Shipping Branch #", required: true %>
              </div>
            <% if @order.account.require_pc_id_number%>
              <div class="col-6">
                <label>PC ID #:</label>
                <%= f.text_field :pc_id_number, class: 'form-control', :placeholder => "PC ID #", required: true %>
              </div>
            <% end %>
          </div>
        </div>

        <br>
        <h6>Billing Details: </h6>
        <br>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :billing_first_name, class: 'form-control', :placeholder => :billing_first_name, required: true %>
            </div>
            <div class="col-6">
              <%= f.text_field :billing_last_name, class: 'form-control', :placeholder => :billing_last_name, required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-8">
              <%= f.text_field :billing_address_line_1, class: 'form-control', :placeholder => "Address", required: true %>
            </div>
            <div class="col-4">
              <%= f.text_field :billing_address_line_2, class: 'form-control', :placeholder => "Apt/Bld #"%>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :billing_city, class: 'form-control', :placeholder => :billing_city, required: true %>
            </div>
            <div class="col-3">
              <%= f.text_field :billing_state, class: 'form-control', :placeholder => :billing_state, required: true %>
            </div>
            <div class="col-3">
              <%= f.text_field :billing_zip_code, class: 'form-control', :placeholder => :billing_zip_code, required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <div class="row">
            <div class="col-6">
              <%= f.text_field :billing_phone_number, class: 'form-control', :placeholder => :billing_phone_number, required: true %>
            </div>
            <div class="col-6">
              <%= f.text_field :billing_email, class: 'form-control', :placeholder => "Email address", required: true %>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label>Billing Branch #:</label>
          <%= f.text_field :billing_branch_number, class: 'form-control', :placeholder => "Billing Branch #", required: true %>
        </div>
        <div class="form-group">
          <%= f.label 'Product Logos:' %>
          <%= f.select(:id, options_from_collection_for_select(@account.product_logos, :id, :name, :selected => @account.product_logos.find_by(name: @order.product_logo_name).id), {:include_blank => 'Choose Logo' },  class: "form-control", required: true ) %>
        </div>
        <div class="row justify-content-md-center">
          <div class="actions">
            <%= f.submit "Send Order", class: 'btn add-to-cart-button' %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-5 offset-1">
      <h6>Order Details:</h6>
      <br>
      <% @order_items.each do |item| %>
        <div class="row billing_order_detail">
            <div class="col-4">
                <%= image_tag(item.color.color_sample_url(:thumb), class: 'd-flex align-self-center img-fluid' )%>
            </div>
            <div class="col-8">
              <p><%= item.product.name %></p>
              <div class="row">
                <div class="col-5">
                  <p><b>Size:</b> <%= item.size.name %></p>
                </div>
                <div class="col-7">
                  <p><b>Quantity:</b> <%= item.quantity %></p>
                </div>
              </div>
              <div class="row">
                <div class="col-8">
                  <p><b>Price:</b> <%= number_to_currency(item.total_price) %></p>
                </div>
                <div class="col-4">
                   <p class="color-circle" style="background: <%= item.color.hex_color %>"></p>
                </div>

              </div>
              <div class="row">

              </div>
            </div>

        </div>
      <% end %>
      <hr>
      <div class="row">
          <%= link_to 'Continue Shopping', account_order_path(@account, @order) %>
      </div>
      <div class="row justify-content-end">
        <h5>TOTAL: <%= number_to_currency(@order.subtotal) %></h5>
      </div>
      <div class="row justify-content-end">
        <p>shipping not included</p>
        <br>
      </div>
      <div class="row justify-content-end">
        <p><%= link_to 'View Invoice Preview', account_order_order_invoice_pdf_path(@account, @order, format: :pdf) %></p>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>

app/views/orders/show.html.erb
<%= render partial: 'layouts/header', locals: { account: @account, order: @order } %>

<br>
<div class="container">
  <p class="text-center">Select a product to start your order, then choose size, quantity and color!</p>
  <div class="row">
    <% @products.order(id: :asc).each do |product| %>
      <div class="col col-4">
        <div class="card product-box">
            <div class="row">
              <div class="col col-6 offset-1">
                <p><%= product.name %></p>
              </div>
              <div class="col col-2 offset-1">
                <p><%= number_to_currency(product.sizes.first.price) unless product.hide_display_price %></p>
              </div>
          </div>
          <div class="card-block">
              <%= image_tag(product.colors.first.color_sample_url(:thumb), class: 'mx-auto d-block product-block-image' )%>
          </div>
          <div class="product-box-button">
                <p class="float-left item-number-cart"><%= product.item_number %></p>
                <%= link_to 'Add To Cart', new_account_order_order_item_path(account_id: @account.id, order_id: @order.id, id: product.id), class: 'btn add-to-cart-button float-right' %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>