config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'

  resources :accounts do
    get :inactive_landing
    
    resources :products do
      delete :color
      delete :size
      post :assign_colors
      post :assign_sizes
    end
    get :order_form
    resources :orders do
      get :shipping_details
      post :shipping_details_save
      resources :order_items do
        delete :delete_item

        collection { post :create_multiple }
      end
      get :order_invoice_pdf
    end

  end

  resources :carts do
  end


  resources :colors

  resources :sizes

  resources :product_logos

end

app/models/account.rb
class Account < ApplicationRecord
  has_many :products
  has_many :orders
  has_many :product_logos

  mount_uploader :logo, LogoUploader
  mount_uploader :favicon_image, FaviconImageUploader

  validates :subdomain, uniqueness: true


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :products_colors
  has_many :products, through: :products_colors
  has_many :order_items

  mount_uploader :color_sample, ColorSampleUploader
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :account

  before_create :set_order_status
  before_save :update_subtotal

  enum status: [:started, :placed, :shipped, :cancelled]



  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private

  def set_order_status
    self.status = 0
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  belongs_to :color
  belongs_to :size

  default_scope { order(ordering_number: :asc) }

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  before_save :finalize



  def unit_price
    if self.persisted?
      self[:unit_price]
    else
      self.product.sizes.find(self[:size_id]).price
    end
  end

  def total_price
    unit_price * quantity
  end

private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end



end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :account
  has_many :products_colors
  has_many :colors, through: :products_colors
  has_many :products_sizes
  has_many :sizes, through: :products_sizes
  has_many :order_items

  default_scope { order(ordering_number: :asc) }


  mount_uploader :product_image, ProductImageUploader

  validates :name, :presence => true
  validates :description, :presence => true
  validates :ordering_number, :presence => true




end

app/models/product_logo.rb
class ProductLogo < ApplicationRecord
  belongs_to :account

  mount_uploader :product_logo_image, ProductLogoImageUploader


end

app/models/products_color.rb
class ProductsColor < ApplicationRecord
  belongs_to :product
  belongs_to :color

end

app/models/products_size.rb
class ProductsSize < ApplicationRecord
  belongs_to :product
  belongs_to :size

end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products_sizes
  has_many :products, through: :products_sizes
  has_many :order_items


  def name_with_price
    "#{ self.name } - #{ helper.number_to_currency(self.price) }"
  end

  private

  def helper
    @helper ||= Class.new do
      include ActionView::Helpers::NumberHelper
    end.new
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.find(params[:order_id])
    @order_items = @order.order_items
    @account = @order.account

  end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @size = Size.new
    @sizes = Size.all
  end

  def create
    @product = Product.find(params[:size][:product_id])
    @size = @product.sizes.create(size_params)
    redirect_to account_product_path(account_id: @product.account_id, id: @product), notice: "Size has been created"
  end



  def destroy
    @products_sizes = ProductsSize.where(size_id: params[:id])
    @products_sizes.destroy_all
    @size = Size.find(params[:id])
    if @size.destroy
      redirect_to new_size_path(product_id: params[:product_id]), notice: "Size has been deleted"
    else  
      redirect_to new_size_path(product_id: params[:product_id]), notice: "There has been an issue deleting the size"
    end
  end



  private


  def size_params
    params.require(:size).permit(:name, :price)
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/carts/_cart_row.html.erb
<div class="container">
  <hr>
  <div class="row ">
    <div class="col-3">
      <%= image_tag(order_item.color.color_sample_url(:thumb), class: 'd-flex align-self-center img-fluid' )%>
    </div>
    <div class="col-3 text-left">
      <h6><%= product.name %></h6>
      <p>Item Number: <%= order_item.product.item_number %></p>
    </div>
      <div class="col-2">
        <p>Size: <%= order_item.size.name %></p>
        <p>Color: <p class="color-circle" style="background: <%= order_item.color.hex_color %>"></p></p>
      </div>
    <div class="col-1">
      <p>Quantity:</p>
      <h4><%= order_item.quantity %></h4>
    </div>
    <div class="col-2">
      <p>Total Price:</p>
      <h4><%= number_to_currency order_item.total_price %></h4>
    </div>
    <div class="col-1">
      <%= link_to 'delete', account_order_order_item_path(@account, @order, order_item), method: :delete %>
    </div>
  </div>
  <hr>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="container text-center">
  <br>
  <h5>Order Status: <%= @order.status.titleize %> </h5>

  <br>
</div>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart. <%= link_to "Shop Now", account_order_path(@account, @order) %>
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, order: @order %>
  <% end %>
<% end %>
<div class="container">
<%= link_to 'Add New Product', account_order_path(@account, @order) %>
</div>

app/views/carts/show.html.erb
<%= render partial: 'layouts/header', locals: { account: @account, order: @order } %>

<div class="container">
  <%= link_to 'Return to Order', account_order_path(@account, @order), class: 'btn btn-outline-secondary add-to-cart-button' %>
  <%= render "shopping_cart" %>

  <div class="row justify-content-end">
    <%= link_to 'Check Out', account_order_shipping_details_path(@account, @order), class: 'btn btn-outline-secondary add-to-cart-button' %>
  </div>
  <div class="row">
    <br>
    <br>
  </div>
</div>

app/views/sizes/_all_sizes.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% sizes.find_each do |size| %>
      <tr>
        <td> <%= size.name %></td>
        <td> <%= number_to_currency(size.price) %></td>
        <td> <%= link_to 'Assign', account_product_assign_sizes_path(account_id: product.account_id, product_id: product.id, id: size.id), method: :post %> </td>
        <td> <%= link_to 'Delete', size_path(account_id: product.account_id, product_id: product.id, id: size.id), method: :delete %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sizes/_new.html.erb
<%= form_for size, {multipart: true, remote: true} do |f| %>
  <div class="row">
    <%= f.hidden_field :product_id, value: "#{@product.id}" %>

    <div class="form-group col-5">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control', id: "example" %>
    </div>

    <div class="form-group col-5">
    <%= f.label :price %>
    <%= f.number_field :price, class: 'form-control', step: 0.05  %>
    </div>

    <div class="actions col-2">
      <p></p>
    <%= f.submit "Add", class: 'btn btn-outline-secondary' %>
    </div>
  </div>
<% end %>

app/views/sizes/_product_sizes.html.erb
<div class="table-responsive">
  <table class="table size_table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Price</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% product.sizes.find_each.with_index do |size, index| %>
      <tr>
        <td> <%= index + 1 %></td>
        <td> <%= size.name %></td>
        <td> <%= number_to_currency(size.price) %></td>
        <td> <%= link_to 'Remove', account_product_size_path(id: size.id, product_id: product.id, account_id: product.account_id), method: :delete %> </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/sizes/create.js.erb
 $(".size_table").html("<%= escape_javascript(render partial: 'sizes/product_sizes', locals: { product: @product}) %>");
 $(".size_table").html("<%= escape_javascript(render partial: 'sizes/new', locals: { product_id: @product.id, size: @new_size}) %>");
 $('.flash').prepend("<div class='alert alert-success'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @message %></div>");

 // $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @message %></div>");

app/views/sizes/destroy.js.erb
<% if @size.destroyed? %>
 $(".size-table").html("<%= escape_javascript(render partial: 'sizes/product_sizes', locals: { product: @product}) %>");

<% else %>
 // $('.flash').prepend("<div class='alert alert-danger'><button type='button' class='close' data-dismiss='alert'>&times;</button><%= @message %></div>");
<% end %>

app/views/sizes/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Back', account_product_path(account_id: @product.account_id, id: @product.id), class: 'btn btn-outline-secondary'%>
  </div>
  <br>
  <div class="row">
    <h3>Current Sizes Available</h3>
  </div>
  <%= render partial: 'sizes/all_sizes', locals: { product: @product, sizes: @sizes} %>
</div>

<div class="container">
  <div class="row">
    <h3>Create New size</h3>
  </div>
<%= render partial: 'sizes/new', locals: { product_id: @product.id, size: @size} %>
</div>