config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'

  resources :accounts do
    get :inactive_landing
    
    resources :products do
      delete :color
      delete :size
      post :assign_colors
      post :assign_sizes
    end
    get :order_form
    resources :orders do
      get :shipping_details
      post :shipping_details_save
      resources :order_items do
        delete :delete_item

        collection { post :create_multiple }
      end
      get :order_invoice_pdf
    end

  end

  resources :carts do
  end


  resources :colors

  resources :sizes

  resources :product_logos

end

app/models/account.rb
class Account < ApplicationRecord
  has_many :products
  has_many :orders
  has_many :product_logos

  mount_uploader :logo, LogoUploader
  mount_uploader :favicon_image, FaviconImageUploader

  validates :subdomain, uniqueness: true


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :products_colors
  has_many :products, through: :products_colors
  has_many :order_items

  mount_uploader :color_sample, ColorSampleUploader
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :account

  before_create :set_order_status
  before_save :update_subtotal

  enum status: [:started, :placed, :shipped, :cancelled]



  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private

  def set_order_status
    self.status = 0
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  belongs_to :color
  belongs_to :size

  default_scope { order(ordering_number: :asc) }

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  before_save :finalize



  def unit_price
    if self.persisted?
      self[:unit_price]
    else
      self.product.sizes.find(self[:size_id]).price
    end
  end

  def total_price
    unit_price * quantity
  end

private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end



end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :account
  has_many :products_colors
  has_many :colors, through: :products_colors
  has_many :products_sizes
  has_many :sizes, through: :products_sizes
  has_many :order_items

  default_scope { order(ordering_number: :asc) }


  mount_uploader :product_image, ProductImageUploader

  validates :name, :presence => true
  validates :description, :presence => true
  validates :ordering_number, :presence => true




end

app/models/product_logo.rb
class ProductLogo < ApplicationRecord
  belongs_to :account

  mount_uploader :product_logo_image, ProductLogoImageUploader


end

app/models/products_color.rb
class ProductsColor < ApplicationRecord
  belongs_to :product
  belongs_to :color

end

app/models/products_size.rb
class ProductsSize < ApplicationRecord
  belongs_to :product
  belongs_to :size

end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products_sizes
  has_many :products, through: :products_sizes
  has_many :order_items


  def name_with_price
    "#{ self.name } - #{ helper.number_to_currency(self.price) }"
  end

  private

  def helper
    @helper ||= Class.new do
      include ActionView::Helpers::NumberHelper
    end.new
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.find(params[:order_id])
    @order_items = @order.order_items
    @account = @order.account

  end
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @color = Color.new
    @colors = Color.all
  end

  def create
    @product = Product.find(params[:color][:product_id])
    @color = @product.colors.create(color_params)
    redirect_to account_product_path(account_id: @product.account_id, id: @product), notice: "Size has been created."
  end

  def destroy
    @products_colors = ProductsColor.where(color_id: params[:id])
    @products_colors.destroy_all
    @color = Color.find(params[:id])
    if @color.destroy
      redirect_to new_color_path(product_id: params[:product_id]), notice: "Color has been deleted"
    else
      redirect_to new_color_path(product_id: params[:product_id]), notice: "There has been an issue deleting the color"
    end
  end


  private


  def color_params
    params.require(:color).permit(:name, :hex_color, :color_sample)
  end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @size = Size.new
    @sizes = Size.all
  end

  def create
    @product = Product.find(params[:size][:product_id])
    @size = @product.sizes.create(size_params)
    redirect_to account_product_path(account_id: @product.account_id, id: @product), notice: "Size has been created"
  end



  def destroy
    @products_sizes = ProductsSize.where(size_id: params[:id])
    @products_sizes.destroy_all
    @size = Size.find(params[:id])
    if @size.destroy
      redirect_to new_size_path(product_id: params[:product_id]), notice: "Size has been deleted"
    else  
      redirect_to new_size_path(product_id: params[:product_id]), notice: "There has been an issue deleting the size"
    end
  end



  private


  def size_params
    params.require(:size).permit(:name, :price)
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/colors/_all_colors.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Hex Color</th>
        <th>Color Sample</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% colors.find_each do |color| %>
      <tr>
        <td> <%= color.name %></td>
        <td> <%= color.hex_color %></td>
        <td> <%= color.color_sample %></td>
        <td> <%= link_to 'Assign', account_product_assign_colors_path(account_id: product.account_id, product_id: product.id, id: color.id), method: :post %> </td>
        <td> <%= link_to 'Delete', color_path(account_id: product.account_id, product_id: product.id, id: color.id), method: :delete, data: {:confirm => "This will delete the color from all products. Are you sure?"}  %> </td>

      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/colors/_new.html.erb
  <%= form_for color, {multipart: true} do |f| %>
    <div class="row">
      <%= f.hidden_field :product_id, value: "#{@product.id}" %>

      <div class="form-group col-4">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, class: 'form-control', id: "example" %>
      </div>

      <div class="form-group col-3">
        <%= f.label :hex_color %>
        <%= f.text_field :hex_color, class: 'form-control'  %>
      </div>

      <div class="form-group col-4">
        <%= f.label :color_sample %>
        <%= f.file_field :color_sample, class: 'form-control'  %>
      </div>

      <div class="actions col-1">
        <p></p>
        <%= f.submit "Add", class: 'btn btn-outline-secondary' %>
      </div>
    </div>
  <% end %>

app/views/colors/_product_colors.html.erb
<div class="table-responsive">
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Hex Color</th>
        <th>View Sample</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% product.colors.find_each.with_index do |color, index| %>
      <tr>
        <td> <%= index + 1 %></td>
        <td> <%= color.name %></td>
        <td> <%= color.hex_color %></td>
        <td> <%= link_to 'View Sample', color.color_sample_url, target: '_blank' %></td>
        <td> <%= link_to 'Remove', account_product_color_path(id: color.id, product_id: product.id, account_id: product.account_id), method: :delete %> </td>
      </tr>
      <% end %>
      <tr>

      </tr>
    </tbody>
  </table>
</div>

app/views/colors/new.html.erb
<div class="container">
  <div class="row">
    <%= link_to 'Back', account_product_path(account_id: @product.account_id, id: @product.id), class: 'btn btn-outline-secondary'%>
  </div>
  <br>
  <div class="row">
    <h3>Current Colors Available</h3>
  </div>
  <%= render partial: 'colors/all_colors', locals: { product: @product, colors: @colors} %>
</div>

<div class="container">
  <div class="row">
    <h3>Create New Color</h3>
  </div>
<%= render partial: 'colors/new', locals: { product_id: @product.id, color: @color} %>
</div>