config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'welcome#home'

  resources :accounts do
    get :inactive_landing
    
    resources :products do
      delete :color
      delete :size
      post :assign_colors
      post :assign_sizes
    end
    get :order_form
    resources :orders do
      get :shipping_details
      post :shipping_details_save
      resources :order_items do
        delete :delete_item

        collection { post :create_multiple }
      end
      get :order_invoice_pdf
    end

  end

  resources :carts do
  end


  resources :colors

  resources :sizes

  resources :product_logos

end

app/models/account.rb
class Account < ApplicationRecord
  has_many :products
  has_many :orders
  has_many :product_logos

  mount_uploader :logo, LogoUploader
  mount_uploader :favicon_image, FaviconImageUploader

  validates :subdomain, uniqueness: true


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/color.rb
class Color < ApplicationRecord
  has_many :products_colors
  has_many :products, through: :products_colors
  has_many :order_items

  mount_uploader :color_sample, ColorSampleUploader
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  belongs_to :account

  before_create :set_order_status
  before_save :update_subtotal

  enum status: [:started, :placed, :shipped, :cancelled]



  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

private

  def set_order_status
    self.status = 0
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
  belongs_to :color
  belongs_to :size

  default_scope { order(ordering_number: :asc) }

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }

  before_save :finalize



  def unit_price
    if self.persisted?
      self[:unit_price]
    else
      self.product.sizes.find(self[:size_id]).price
    end
  end

  def total_price
    unit_price * quantity
  end

private

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end



end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :account
  has_many :products_colors
  has_many :colors, through: :products_colors
  has_many :products_sizes
  has_many :sizes, through: :products_sizes
  has_many :order_items

  default_scope { order(ordering_number: :asc) }


  mount_uploader :product_image, ProductImageUploader

  validates :name, :presence => true
  validates :description, :presence => true
  validates :ordering_number, :presence => true




end

app/models/product_logo.rb
class ProductLogo < ApplicationRecord
  belongs_to :account

  mount_uploader :product_logo_image, ProductLogoImageUploader


end

app/models/products_color.rb
class ProductsColor < ApplicationRecord
  belongs_to :product
  belongs_to :color

end

app/models/products_size.rb
class ProductsSize < ApplicationRecord
  belongs_to :product
  belongs_to :size

end

app/models/size.rb
class Size < ApplicationRecord
  has_many :products_sizes
  has_many :products, through: :products_sizes
  has_many :order_items


  def name_with_price
    "#{ self.name } - #{ helper.number_to_currency(self.price) }"
  end

  private

  def helper
    @helper ||= Class.new do
      include ActionView::Helpers::NumberHelper
    end.new
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :order_form]

  def new
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      redirect_to account_path(@account), notice: 'Account has been created successfully!'
    else
      redirect_to new_account_path, alert: 'There was an error creating the account'
    end
  end

  def index
    @accounts = Account.all
    session[:account_id] = nil
  end

  def show
    @products = @account.products.order(:ordering_number)
    @product_logos = @account.product_logos
  end

  def edit
  end


  def update
    @account.assign_attributes(account_params)
    if @account.save
      redirect_to account_path(@account), notice: 'Account has been updated successfully!'
    else
      redirect_to edit_account_path(@account), alert: 'There was an issue updating this account. Please try again!'
    end
  end


  def order_form
    @products = @account.products.order(:ordering_number)
    @order_items = current_order.order_items
  end

  def destroy
    if @account.destroy
      redirect_to accounts_path, notice: 'Account deleted successfully.'
    else
      redirect_to @account, alert: 'There was an issue deleting the account.'
    end
  end

  def inactive_landing
    @account = Account.find(params[:account_id])
  end

  private

  def set_account
    @account = Account.find(params[:id])
    session[:account_id] = @account.id
  end

  def account_params
    params.require(:account).permit(:business_name, :contact_first_name, :contact_last_name, :address_line_1, :address_line_2, :address_line_2, :city,
        :state, :zip_code, :country, :website, :phone_number, :phone_number_extension, :fax_number, :email_address, :subdomain, :logo, :order_form_subheading, :orders_due_by, :order_special_message, :active, :favicon_image, :require_pc_id_number
    )
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order = Order.find(params[:order_id])
    @order_items = @order.order_items
    @account = @order.account

  end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController

  def new
    @product = Product.find(params[:product_id])
    @size = Size.new
    @sizes = Size.all
  end

  def create
    @product = Product.find(params[:size][:product_id])
    @size = @product.sizes.create(size_params)
    redirect_to account_product_path(account_id: @product.account_id, id: @product), notice: "Size has been created"
  end



  def destroy
    @products_sizes = ProductsSize.where(size_id: params[:id])
    @products_sizes.destroy_all
    @size = Size.find(params[:id])
    if @size.destroy
      redirect_to new_size_path(product_id: params[:product_id]), notice: "Size has been deleted"
    else  
      redirect_to new_size_path(product_id: params[:product_id]), notice: "There has been an issue deleting the size"
    end
  end



  private


  def size_params
    params.require(:size).permit(:name, :price)
  end


end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <br>
      <%= link_to 'Back', @account, class: 'btn btn-outline-secondary' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class='col-md-6'>
      <div class="card">
        <div class="card-header">
          Add Account
        </div>
        <div class="card-block">
          <%= form_for @account do |f| %>
            <div class="form-group">
              <%= f.label :active %><br />
              <%= f.check_box :active, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :business_name %><br />
              <%= f.text_field :business_name, autofocus: true, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :subdomain %><br />
              <%= f.text_field :subdomain, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :contact_first_name %><br />
              <%= f.text_field :contact_first_name, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :contact_last_name %><br />
              <%= f.text_field :contact_last_name, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :address_line_1 %><br />
              <%= f.text_field :address_line_1, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :address_line_2 %><br />
              <%= f.text_field :address_line_2, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :city %><br />
              <%= f.text_field :city, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :state %><br />
              <%= f.text_field :state, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :zip_code %><br />
              <%= f.number_field :zip_code, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :country %><br />
              <%= f.text_field :country, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :website %><br />
              <%= f.text_field :website, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :phone_number %><br />
              <%= f.text_field :phone_number, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :phone_number_extension %><br />
              <%= f.text_field :phone_number_extension, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :fax_number %><br />
              <%= f.text_field :fax_number, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :email_address %><br />
              <%= f.text_field :email_address, class: 'form-control' %>
            </div>


            <div class="form-group">
              <%= f.label :order_form_subheading %><br />
              <%= f.text_field :order_form_subheading, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :order_special_message %><br />
              <%= f.text_area :order_special_message, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :orders_due_by %><br />
              <%= f.date_field :orders_due_by, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :require_pc_id_number %><br />
              <%= f.check_box :require_pc_id_number, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label 'Account Logo' %>
              <%= f.file_field :logo, class: 'form-control'  %>
            </div>

            <div class="form-group">
              <%= f.label 'Account Favicon Image' %>
              <%= f.file_field :favicon_image, class: 'form-control'  %>
            </div>


            <div class="actions">
              <%= f.submit "Update", class: 'btn btn-outline-secondary' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/inactive_landing.html.erb
<div class="container">
    <h1>Sup</h1>
</div>

app/views/accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <br>
      <%= link_to 'Back', root_path, class: 'btn btn-outline-secondary' %>
    </div>
  </div>
  <br>
  <div class="row justify-content-md-center">
    <div class="col col-4">
      <h3 class="text-center">All Accounts</h3>
    </div>
  </div>
  <% if current_user %>
    <div class="row">
        <%= link_to 'Add Account', new_account_path, class: 'btn btn-outline-secondary' %>
    </div>
  <% end %>
  <div class="row">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Business Name</th>
        <th>Domain</th>
        <th>Email</th>
        <th>Phone Number</th>

      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |a| %>
      <tr>
        <th scope="row"> <%= link_to 'view', account_path(id: a.id),  class: 'btn btn-outline-secondary btn-sm' %> </th>
        <td><%= a.business_name %></td>
        <td><%= a.subdomain %></td>
        <td><%= a.email_address %></td>
        <td><%= a.phone_number %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <br>
      <%= link_to 'Back', root_path, class: 'btn btn-outline-secondary' %>
    </div>
  </div>
  <br>
  <div class="row">
    <div class='col-md-6'>
      <div class="card">
        <div class="card-header">
          Add Account
        </div>
        <div class="card-block">
          <%= form_for @account do |f| %>
            <div class="form-group">
              <%= f.label :business_name %><br />
              <%= f.text_field :business_name, autofocus: true, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :subdomain %><br />
              <%= f.text_field :subdomain, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :contact_first_name %><br />
              <%= f.text_field :contact_first_name, class: 'form-control', required: true %>
            </div>
            <div class="form-group">
              <%= f.label :contact_last_name %><br />
              <%= f.text_field :contact_last_name, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :address_line_1 %><br />
              <%= f.text_field :address_line_1, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :address_line_2 %><br />
              <%= f.text_field :address_line_2, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :city %><br />
              <%= f.text_field :city, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :state %><br />
              <%= f.text_field :state, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :zip_code %><br />
              <%= f.number_field :zip_code, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :country %><br />
              <%= f.text_field :country, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :website %><br />
              <%= f.text_field :website, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :phone_number %><br />
              <%= f.text_field :phone_number, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :phone_number_extension %><br />
              <%= f.text_field :phone_number_extension, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :fax_number %><br />
              <%= f.text_field :fax_number, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :email_address %><br />
              <%= f.text_field :email_address, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label :order_form_subheading %>
              <%= f.text_field :order_form_subheading, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :order_special_message %>
              <%= f.text_area :order_special_message, class: 'form-control' %>
            </div>

            <div class="form-group">
              <%= f.label :orders_due_by %><br />
              <%= f.date_field :orders_due_by, class: 'form-control', required: true %>
            </div>

            <div class="form-group">
              <%= f.label 'Account Logo' %>
              <%= f.file_field :logo, class: 'form-control', required: true  %>
            </div>

            <div class="form-group">
              <%= f.label 'Account Favicon Image' %>
              <%= f.file_field :favicon_image, class: 'form-control', required: true  %>
            </div>

            <div class="actions">
              <%= f.submit "Create", class: 'btn btn-outline-secondary' %>
            </div>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <br>
      <% if current_user %>
        <%= link_to 'Back', accounts_path, class: 'btn btn-outline-secondary' %>
        <%= link_to 'Edit', edit_account_path(@account), class: 'btn btn-outline-secondary'   %>
        <%= link_to 'Delete Account', account_path(@account), class: 'btn btn-outline-danger', method: :delete, data: { confirm: 'Are you sure you want to delete this account? It cannot be undone.' }   %>
      <% end %>
    </div>
  </div>
  <br>
</div>
<div class="container">
    <div class="row justify-content-md-center">
      <div class="col col-md-auto">
        <%= image_tag(@account.logo_url, class: 'd-flex align-self-center header-logo-image' )%>
      </div>
    </div>
    <div class="row justify-content-md-center">
      <div class="col col-md-auto">
        <h2> <%= @account.business_name %> </h2>
        <hr class="my-4">

      </div>
    </div>
    <div class="row justify-content-md-center">
      <% if @account.active %>
        <div class="col col-md-auto">
          <%= link_to "Create #{@account.order_form_subheading}", new_account_order_path(@account), class: 'btn btn-primary' %>
        </div>
      <% else %>
      <div class="col text-center">
        <h3><%= "#{ @account.order_form_subheading } has officially completed" %></h3>
        <br>
        <h5><%= "Please come back during our next bulk ordering program." %></h5>
      </div>
      <% end %>
    </div>
    <% if current_user %>
      <div class="row justify-content-md-center">
        <div class="col col-lg-8 col-md-12">
          <br>
          <div class="card">
            <div class="card-header">
              Products - <%= link_to 'Add Product', new_account_product_path(@account) %>
            </div>
            <div class="card-block">
              <table class="table">
                <thead>
                  <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Item Number</th>
                    <th>Ordering Number</th>
                    <th>Active</th>
                  </tr>
                </thead>
                <tbody>
                  <% @products.each do |prod| %>
                  <tr>
                    <td scope="row"> <%= link_to 'view', account_product_path(account_id: @account.id, id: prod.id),  class: 'btn btn-outline-secondary btn-sm' %> </td>
                    <td><%= prod.name %></td>
                    <td><%= prod.item_number %></td>
                    <td><%= prod.ordering_number %></td>
                    <td>
                      <% if prod.active? %>
                        <%= fa_icon "check" %>
                      <% else %>
                        <%= fa_icon "close" %>
                      <% end %>
                    </td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <div class="col col-lg-4 col-md-12">
          <br>
          <div class="card">
            <div class="card-header">
              Product Logos - <%= link_to 'Add Product Logos', new_product_logo_path(account_id: @account.id) %>
            </div>
            <div class="card-block">
              <table class="table">
                <thead>
                  <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  <% @product_logos.find_each.with_index do |logo, index| %>
                  <tr>
                    <td> <%= index + 1 %></td>
                    <td><%= logo.name %></td>
                    <td><%= link_to 'View', logo.product_logo_image.url %> | <%= link_to 'Delete', product_logo_path(logo.id), method: :delete %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    <% end %>


</div>